### ISSUE TITLE
[Feat] Queue

### ISSUE THREAD

**Issue by Timber1900** [Timber1900/WebDL_Android#2]
- WedDL for android should have a queue system similar to the windows versions, it should
  - Display the video's thumbnail/title,
  - Allow for title to be modified,
  - Allow for selecting between video and audio,
  - Allow the selection of quality

## TODO
- [x] Implement the queue context
- [x] Create the UI for the queue
- [x] Implement video renaming
- [x] Implement extension choosing
- [ ] Implement quality selector
- [x] Implement queue storage 
  - We'll use https://react-native-async-storage.github.io/async-storage/ for this
